//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionClinique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratoire
    {
        public int Id { get; set; }
        public int IdPatient { get; set; }
        public int IdExamen { get; set; }
        public string Observation { get; set; }
        public System.DateTime DateAnalyse { get; set; }
    
        public virtual Examan Examan { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
