//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionClinique
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traitement
    {
        public int Id { get; set; }
        public int IdMedecin { get; set; }
        public int IdMaladie { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public string EtatFinal { get; set; }
    
        public virtual Maladie Maladie { get; set; }
        public virtual Medecin Medecin { get; set; }
    }
}
